export class Articles{
        id?: number;
        uom_id?: string;	
        user_id?: number;
        category_id?: number;
        name?: string;
        description?: string;
        type?: string;
        codebar?: string;
        code_manuel?: string;
        photo?: string;
        point?: number;
        nbrgros?: number;
        bonus_applicable?: boolean;
        has_vat?: boolean;
        available_qte?: number;
        selling_qte?: number;
        category_name?: string;
        uom_name?: string;
        uom_symbol?: string;
        money_id?: number;
        default_money?: number;
        default_money_abreviation?: string;
        prices?: any;
        price?: number;
        uom_abreviation?: string;
        abreviation?: string;
        service?: any;
        selected?: boolean;
        total?: number;
        sync_status?: string;
        status?:string;
        deposit_id?:any;
        provider_id?:any;
        quantity?: number;
        expiration_date?: string;
        motif?:string;
        note?:string;
        palette?: string;
        index?: number;
        done_at?: string;
        deposit_mistaken?: boolean;
        quantity_mistaken?: boolean;
        price_mistaken?:boolean;
        service_usage?:string;
        subservices?:any;
        serial_numbers?:any;
}