import { AnyARecord } from "dns";

export interface Invoice{
    id?: number;
    edited_by_id?: number;
    user_name?: string;
    full_name?: string;
    customer_id?: number;
    customer_uuid?: number;
    customer_name?: string;
    custome_phone?: string;
    total?: number;
    total_ht?: number;
    totalespeces?: number;
    totalcreditcard?: number;
    totalmobilemoney?: number;
    money?:any;
    money_id?: number;
    money_name?: string;
    abreviation?: string;
    type_facture?: string;
    amount_paid?: number;
    payment_mode?: string;
    ref_payment?: string;
    discount?: number;
    vat_percent?: number;
    vat_amount?: number;
    back?: number;
    is_validate_discount?: boolean;
    enterprise_id?: number;
    note?: string;
    servant_id?: number;
    servant_name?: string;
    table_id?: number;
    table_name?: string;
    details?: any; 
    customer?:any;
    table?:any;
    servant?:any;
    deposit?:any;
    created_at?: string;
    updated_at?: string;
    updated_At?:string;
    invoice?: any;
    after_validation?: string;
    sync_status?: string;
    status?: string;
    uuid?: string;
    total_received?: number;
    netToPay?:0;
    done_at?:string;
    date_operation?:string;
    noteArray?:string[];
}