export class StockHistory{
    id?: number;
    service_name?: string;
    description?: string;
    uom_name?: string;
    uom_symbol?: string;
    depot_id?: number;
    deposit_name?: string;	
    service_id?: number;
    user_id?: number;
    done_by_name?: string;
    done_at?: string;
    date_operation?: string;
    quantity?: number;
    quantity_before?: number;
    price?: number;
    expiration_date?: string;
    bon_livraison?: string;
    motif?: string;
    invoice_id?: number;
    code_bar?: string;
    note?: string;
    type?: string;
    total?: number;
    customer_id?: number;
    provider_id?: number;
    providerName?:string;
    document_type?: number;
    document_name?: string;
    document_number?: string;
    type_approvement?: string;
    attachment?: string;
    status?: string;
    uuid?:string;
    showWithdraw? : boolean;
    showbarcode?: boolean;
    showpu?: boolean;
    showtotal?: boolean;
    showcalendar?: boolean;
    created_at?:string;
    selected?:boolean;
    read?:boolean;
    enterprise_id?: number;
    sync_status?: string;
}