export const permission  = [
    {router:'/home',name:'Facturation',imgSrc:'',icon:'cart',avatar_class:'',type: 'menu',
    "action":[
      {action:"all",value:false,french:"Tout"},
      {action:"view",value:false,french:"Voir"},
      {action:"add",value:false,french:"Ajouter"},
      {action:"edit",value:false,french:"Modifier"},
      {action:"delete",value:false,french:"Supprimer"},
      {action:"can sell",value:false,french:"Peut vendre"},
      {action:"cash",value:false,french:"Vendre cash"},
      {action:"credit",value:false,french:"Vendre crédit"},
      {action:"Payer credit",value:false,french:"Payer crédit"},
      {action:"proforma",value:false,french:"Facture Proforma"},
      {action:"duplicate",value:false,french:"Facture Duplicata"},
      {action:"tva change",value:false,french:"Peut modifier la TVA"},
      {action:"give reduction",value:false,french:"Peut accorder une réduction"},
      {action:"invoice paused",value:false,french:"Mettre la facture en pause"},
      {action:"change pos settings",value:false,french:"Changer les configurations POS"},
      {action:"change print settings",value:false,french:"Changer les paramètres de l'imprimante"},
      {action:"change default print format",value:false,french:"Changer l'imprimante par défaut"},
      {action:"partager",value:false,french:"Partager la facture"},
      {action:"Invoice message footer",value:false,french:"Configurer le pied de page"},
    ]},
    {router:'/departements',name:'departements',imgSrc:'',icon:'cart',avatar_class:'',type: 'menu',
    "action":[
      {action:"all",value:false,french:"Tout"},
      {action:"view",value:false,french:"Voir"},
      {action:"add",value:false,french:"Ajouter"},
      {action:"edit",value:false,french:"Modifier"},
      {action:"delete",value:false,french:"Supprimer"},
      {action:"affect_user",value:false,french:"Affecter agent"}
    ]},
    {router:'/uzisha/articles/catalogue',name:'produits',imgSrc:'',icon:'text',avatar_class:'',type: 'menu',
    "action":[
      {action:"all",value:false,french:"Tout"},
      {action:"view",value:false,french:"View"},
      {action:"add",value:false,french:"Ajouter"},
      {action:"edit",value:false,french:"Modifier"},
      {action:"delete",value:false,french:"Supprimer"},
    ]},{router:'/uzisha/sponsorship',name:'Parrainage',imgSrc:'',icon:'paw',avatar_class:'',type: 'menu',"action":[
      {action:"all",value:false,french:"Tout"},
      {action:"view",value:false,french:"View"},
      {action:"add",value:false,french:"Ajouter"},
      {action:"edit",value:false,french:"Modifier"},
      {action:"delete",value:false,french:"Supprimer"},
    ]},
    {router:'/uzisha/customers',name:'clients',imgSrc:'',icon:'people',avatar_class:'',type: 'menu',
    "action":[
      {action:"all",value:false,french:"Tout"},
      {action:"view",value:false,french:"Voir"},
      {action:"add",value:false,french:"Ajouter"},
      {action:"edit",value:false,french:"Tout"},
      {action:"delete",value:false,french:"Supprimer"},
    ]},
    {router:'/uzisha/stock',name:'stock',imgSrc:'',icon:'layers',avatar_class:'',type: 'menu',
    "action":[
      {action:"all",value:false,french:"Tout"},
      {action:"view",value:false,french:"Voir"},
      {action:"add",value:false,french:"Ajouter"},
      {action:"edit",value:false,french:"Modifier"},
      {action:"delete",value:false,french:"Supprimer"},
      {action:"stock valuation",value:false,french:"Valeur de stock"},
      {action:"entry",value:false,french:"Entrée stock"},
      {action:"withdraw",value:false,french:"Sortie stock"},
      {action:"make ask",value:false,french:"Demande approvisionnement"},
      {action:"validate ask",value:false,french:"Valider une demande"},
      {action:"make transfer",value:false,french:"Faire un transfert de stock"},
      {action:"validate_transfer",value:false,french:"Valider un transfert de stock"},
    ]},
    {router:'/uzisha/agents',name:'agents',imgSrc:'',icon:'person',avatar_class:'',type: 'menu',
    "action":[
      {action:"all",value:false,french:"Tout"},
      {action:"view",value:false,french:"Voir"},
      {action:"add",value:false,french:"Ajouter"},
      {action:"edit",value:false,french:"Modifier"},
      {action:"delete",value:false,french:"Supprimer"},
      // {action:"access",value:false,french:""},
    ]},
    {router:'/uzisha/deposits',name:'dépôts',imgSrc:'',icon:'document',avatar_class:'',type: 'menu',
    "action":[
      {action:"all",value:false,french:"Tout"},
      {action:"view",value:false,french:"Voir"},
      {action:"add",value:false,french:"Ajouter"},
      {action:"edit",value:false,french:"Modifier"},
      {action:"view inventory",value:false,french:"Voir inventaire"},
      {action:"delete",value:false,french:"Supprimer"},
    
    ]},
    {router:'/uzisha/tables',name:'tables',imgSrc:'',icon:'barbell',avatar_class:'', type: 'submenu',
    "action":[
      {action:"all",value:false,french:"Tout"},
      {action:"view",value:false,french:"Voir"},
      {action:"add",value:false,french:"Ajouter"},
      {action:"edit",value:false,french:"Modifier"},
      {action:"delete",value:false,french:"Supprimer"},
    ]},  
    {router:'/uzisha/categories',name:'services categories',imgSrc:'',icon:'barbell',avatar_class:'', type: 'submenu',
    "action":[
      {action:"all",value:false,french:"Tout"},
      {action:"view",value:false,french:"Voir"},
      {action:"add",value:false,french:"Ajouter"},
      {action:"edit",value:false,french:"Modifier"},
      {action:"delete",value:false,french:"Supprimer"},
    ]},
    {router:'/uzisha/uom',name:'uom',imgSrc:'',icon:'barbell',avatar_class:'', type: 'submenu',
    "action":[
      {action:"all",value:false,french:"Tout"},
      {action:"view",value:false,french:"Voir"},
      {action:"add",value:false,french:"Ajouter"},
      {action:"edit",value:false,french:"Modifier"},
      {action:"delete",value:false,french:"Supprimer"},
    ]},
    {router:'/uzisha/servants',name:'serveurs',imgSrc:'',icon:'people',avatar_class:'', type: 'submenu',
    "action":[
      {action:"all",value:false,french:"Tout"},
      {action:"view",value:false,french:"Voir"},
      {action:"add",value:false,french:"Ajouter"},
      {action:"edit",value:false,french:"Modifier"},
      {action:"delete",value:false,french:"Supprimer"},
    ]},
    {router:'/uzisha/orders',name:'commandes',imgSrc:'',icon:'beaker',avatar_class:'', type: 'submenu',
    "action":[
      {action:"all",value:false,french:"Tout"},
      {action:"view",value:false,french:"Voir"},
      {action:"add",value:false,french:"Ajouter"},
      {action:"edit",value:false,french:"Modifier"},
      {action:"delete",value:false,french:"Supprimer"},
    ]},
    {router:'/uzisha/finances/invoices',name:'factures',imgSrc:'',icon:'cart',avatar_class:'', type: 'submenu',
    "action":[
      {action:"all",value:false,french:"Tout"},
      {action:"view",value:false,french:"Voir"},
      {action:"add",value:false,french:"Ajouter"},
      {action:"edit",value:false,french:"Modifier"},
      {action:"delete",value:false,french:"Supprimer"},
    ]},
    {router:'/uzisha/finances/expenditures',name:'depenses',imgSrc:'',icon:'cash',avatar_class:'', type: 'submenu',
    "action":[
      {action:"all",value:false,french:"Tout"},
      {action:"view",value:false,french:"Voir"},
      {action:"add",value:false,french:"Ajouter"},
      {action:"edit",value:false,french:"Modifier"},
      {action:"delete",value:false,french:"Supprimer"},
      {action:"partager",value:false,french:"Partager dépense"},
    ]},
    {router:'/uzisha/othersentries',name:'Entrée argent',imgSrc:'',icon:'add',avatar_class:'', type: 'submenu',
    "action":[
      {action:"all",value:false,french:"Tout"},
      {action:"view",value:false,french:"Voir"},
      {action:"add",value:false,french:"Ajouter"},
      {action:"edit",value:false,french:"Modifier"},
      {action:"delete",value:false,french:"Supprimer"},
      {action:"partager",value:false,french:"Partager entrée argent"},
    ]},
    {router:'/uzisha/finances/fences',name:'clôtures',imgSrc:'',icon:'exit',avatar_class:'', type: 'submenu',
    "action":[
      {action:"all",value:false,french:"Tout"},
      {action:"view",value:false,french:"Voir"},
      {action:"add",value:false,french:"Ajouter"},
      {action:"edit",value:false,french:"Modifier"},
      {action:"delete",value:false,french:"Supprimer"},
      {action:"turn back",value:false,french:"Retourner"},
      {action:"receive",value:false,french:"Recevoir clôture"},
      {action:"correct",value:false,french:"Corriger la clotûre"},
      {action:"send",value:false,french:"Envoyter clôture"}
    ]},
    {router:'/uzisha/accounts',name:'comptes',imgSrc:'',icon:'book-outline',avatar_class:'', type: 'submenu',
    "action":[
      {action:"all",value:false,french:"Tout"},
      {action:"view",value:false,french:"Voir"},
      {action:"add",value:false,french:"Ajouter"},
      {action:"edit",value:false,french:"Modifier"},
      {action:"delete",value:false,french:"Supprimer"},
    ]},
    {router:'/uzisha/providers',name:'fournisseurs',imgSrc:'',icon:'person-outline',avatar_class:'', type: 'submenu',
    "action":[
      {action:"all",value:false,french:"Tout"},
      {action:"view",value:false,french:"Voir"},
      {action:"add",value:false,french:"Ajouter"},
      {action:"edit",value:false,french:"Modifier"},
      {action:"delete",value:false,french:"Supprimer"},
    ]},
    {router:'/uzisha/generalreport',name:'Marge brute',imgSrc:'',icon:'document',avatar_class:'', type: 'submenu',
    "action":[
      {action:"all",value:false,french:"Tout"},
      {action:"view",value:false,french:"Voir"},
      {action:"add",value:false,french:"Ajouter"},
      {action:"edit",value:false,french:"Modifier"},
      {action:"delete",value:false,french:"Supprimer"},
    ]},
  //   {router:'/uzisha/pointofsales',name:'POS',imgSrc:'',icon:'location',avatar_class:'',type:'menu',
  //   "action":[
  //     {action:"all",value:false},
  //     {action:"view",value:false},
  //     {action:"add",value:false},
  //     {action:"edit",value:false},
  //     {action:"delete",value:false},
  //     {action:"affect users",value:false},
  //     {action:"affect services",value:false},
  //   ]
  // },
  {router:'/uzisha/reports',name:'Rapports',imgSrc:'',icon:'stats-chart-outline',avatar_class:'',type:'menu',
    "action":[
      {action:"all",value:false,french:"Tout"},
      {action:"view",value:false,french:"Voir"},
      {action:"stock",value:false,french:"Rapport de stock"},
      {action:"sell",value:false,french:"Rapport de vente"},
      {action:"finances",value:false,french:"dépenses et entrées"},
      {action:"cashbook",value:false,french:"Livre de caisse"},
      {action:"others",value:false,french:"Autres rapports"},
    ]
  },  
  {router:'/uzisha/tubs',name:'Caisses',imgSrc:'',icon:'book-outline',avatar_class:'',type:'menu',
    "action":[
      {action:"all",value:false,french:"Tout"},
      {action:"view",value:false,french:"Voir"},
      {action:"add",value:false,french:"Ajouter"},
      {action:"entry",value:false,french:"Entrées"},
      {action:"withdraw",value:false,french:"Sorties"},
      {action:"report",value:false,french:"Rapports"},
    ]
  },
  {router:'/uzisha/enterprises',name:'Entreprise',imgSrc:'',icon:'home-outline',avatar_class:'',type:'menu',
    "action":[
      {action:"all",value:false,french:"Tout"},
      {action:"view",value:false,french:"Voir"},
      {action:"edit",value:false,french:"Modifier"},
      {action:"delete",value:false,french:"Supprimer"},
    ]
  }, 
  {router:'/uzisha/settingmargins',name:'Marges dépenses',imgSrc:'',icon:'reader-outline',avatar_class:'',type:'submenu',
    "action":[
      {action:"all",value:false,french:"Tout"},
      {action:"view",value:false,french:"Voir"},
      {action:"edit",value:false,french:"Modifier"},
      {action:"delete",value:false,french:"Supprimer"},
      {action:"affect users",value:false,french:"Affecter agents"}
    ]
  },
  {router: "/uzisha/sycingdata",name: "syncing",imgSrc: "",icon: "",avatar_class: "",type: "autre",
    "action": [
        {action: "send",value: false,french:"Envoyer"},
        {action: "receive",value: false,french:"Recevoir"},
        {action: "offline",value: false,french:"Travailler sans connexion internet"},
        {action: "online",value: false,french:"Travailler avec connexion internet"}]
  }
]
